### PR TITLE
feat: Improve readability color scheme

### PR DESCRIPTION
**Pull request by hnsstrk**
## Pull Request Checklist

1. **Documentation**: I documented the changes within the code where necessary.
2. **Target Branch**: This PR targets the `develop` branch (not the `master` branch).
3. **Testing**: I changed the readability color scheme and tested the changes on three different monitors for visibility and readability.
4. **Lint and Tests**: I have **not** run `yarn lint` or `yarn test` (please advise if this is necessary).
5. **Changelog Entry**: I have **not** added an entry to `CHANGELOG.md` (please let me know if I should add this).
6. **Code Style**: I matched my code style to the repository as much as possible.
7. **GPL License**: I agree that my code will be published under the GNUP GPL v3 license.
8. **New Files**: No new files were created.
9. **Git Pull**: I ran `git pull` before creating this PR to ensure there are no merge conflicts.

## Description
Updated readability color scheme to reflect the traffic light system (red, yellow, green) for better user comprehension.

## Changes

- Updated the readability color scheme to use a traffic light system: red for poor readability, yellow for average readability, and green for good readability.
- Modified the corresponding CSS classes to reflect the new color scheme.
- Updated comments in the code to explain the new readability logic.
- No breaking API changes were introduced with these modifications.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Wonderful, thanks for opening the PR! There's nothing to worry about regarding the linter since you really just exchanged color codes. Did you run these changes once real quick to confirm that the appropriate colors show up? If yes, I'll quickly merge, and we can have this in the upcoming release. Please get back to me until, say, Tuesday so that I know!

**Comment by hnsstrk** [comment]
Hi Hendrik,

thanks for the quick response and for your support!

I'm currently trying to set up the build environment so I can run the tests and verify the changes. I expect to have everything sorted out and tested by tomorrow, and I'll get back to you then.

**Comment by hnsstrk** [comment]
I have tested the changes, and the colors look great and are distinguishable as expected.

**Comment by nathanlesage** [comment]
Amazing, thank you very much! Then I'll merge it to include it in the upcoming release – should some colors turn out less than ideal, we can still adjust them after the fact. Thanks for your great work and the thought you put into this!

**Pull request merged**
