### PR TITLE
Translation/ru ru

### PR DESCRIPTION
**Pull request by krote5k**
full russian translate

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you very much for your work in translating the application! Before we can merge, please resolve the conflicts that prevent me from doing so. Also, you have only committed the `*.mo`-file, not the `*.po`-file. Zettlr uses the latter and does not make use of the compiled versions.

**Comment by krote5k** [comment]
Poedit seems to have mixed the strings and now the strings that were untranslated do not conflict with the translated ones.

**Comment by nathanlesage** [comment]
There are somehow still merge conflicts, maybe the weekly translation update now conflicts with your changes …? (I know I have to get back to it at some point and fix the translation updater script as well)

**Comment by nathanlesage** [comment]
There are somehow still merge conflicts. I do not know what is happening, but to speed things up: would you allow me to simply copy and paste your work directly into the dev branch? This may make things quicker.

**Comment by krote5k** [comment]
> There are somehow still merge conflicts. I do not know what is happening, but to speed things up: would you allow me to simply copy and paste your work directly into the dev branch? This may make things quicker.

It will be the surest way.

**Comment by nathanlesage** [comment]
Wonderful, thank you. It is now in the codebase. Thank you again for your work and help.

**Pull request closed without merging**
