### PR TITLE
Upgrade eslint-plugin-jquery to eslint-plugin-no-jquery 2.5.0

### PR DESCRIPTION
**Pull request by edg2s**
##  Description

Use a newer plugin for linting jQuery usage.

## Changes

Replaces uses of deprecated event shorthands with on/trigger.

## Additional information

Tested on: <!-- OS including version ->

### CODE REVIEW

**Comment by edg2s** [comment]
Lint errors don't appear to be related to the changes here?

**Comment by nathanlesage** [comment]
The linter currently fails due to the TypeScript migrations, so I assume not. I'll have a look tomorrow!

**Comment by nathanlesage** [comment]
Would you mind updating your PR to match the newly refactored editor? That would be awesome!

Btw: Single-line-statements in the form of `$('#css-id').focus()` can immediately be repaced by `document.getElementById('#css-id').focus()` so that we don't have to double-touch these lines later on!

Otherwise, looks good!

**Comment by edg2s** [comment]
Updated. Errors seem unrelated again.

**Comment by edg2s** [comment]
BTW if you are aiming to get rid of jQuery completely you could use the no-jquery/all config

**Review by nathanlesage — APPROVED** [review]

**Comment by nathanlesage** [comment]
> BTW if you are aiming to get rid of jQuery completely you could use the no-jquery/all config

Nah, this will introduce all errors at once, we're currently following the path "Add one rule as error, fix all errors", so a gradually adoption, which works fine so far!

Concerning the unit tests – are you sure you pulled my recent commits? Because locally the tests run fine, and it looks like the moment-based test fails again for you, and I'm unsure what this means

**Comment by edg2s** [comment]
The stack is currently based on ab64a5096fc8d97bea8470755ece9f07afaa46c8, which is from today. I can rebase again...

**Comment by edg2s** [comment]
This issue is still relevant.

**Pull request closed without merging**
