### PR TITLE
feat: Project Overhaul

### LINKED ISSUE #4966: Project Glob Patterns are a Pain to Work with
### Description

I still am questioning my decision of being extra fancy and allowing for glob patterns to select which files (and in which order) will be included in a project export.

I just had to move around a bunch of files just to ensure that they weren't included because I literally had no idea how to appropriately adapt the glob patterns.

### Reproducing

Make a folder a project; apply some glob patterns to try to ensure that only the right files are exported. If you aren't completely careful, this will not work.

### Zettlr Version

Right off the develop branch

### Specify version

_No response_

### Installation Method

None

### Your Platform

- [ ] Windows
- [X] macOS
- [ ] Linux

### Architecture

- [ ] Intel 64bit
- [X] ARM 64bit

### Operating System Version

Sonoma 14.3.2

### Additional Information

Why did so few people complain about this …? Do y'all just not have encountered this issue, or don't you use the project feature …? 👀 

@sensologica Something you may want to take a stab at, since it's 99% user experience.

### PR DESCRIPTION
**Pull request by nathanlesage**
## Description

The project feature is one of the oldest in Zettlr, stemming from `v0.18.0` from July 2018. However, for basically the entire past six years, the project feature has attempted to piggyback on the way the files in your project directory were displayed in the file manager. The initial assumptions were (a) all files need to be exported and (b) the visible sorting (by name or time) is a sufficient amount of control over the project build step.

However, I was wrong. Over time, many important features have made it into the app, such as displaying YAML titles or H1 headings instead of the filenames. Now that Zettlr is such a powerful tool, you likely don't just have the actual project files in a project directory, but likely notes, minutes, and miscellaneous files as well.

The previous change to add glob patterns that allow for subsetting of the files and excluding files was a little improvement. However, it was (a) extremely difficult to understand (even for me, see below) and (b) it still did not solve the issue with the export order.

This PR introduces a technically extremely simple change that has a ton of potential for wielding actual control over your projects.

### At a glance

* Removed the `filters` array of Zettlr projects (within the `.ztr-directory`-files)
* Added a `files` array there, that hold paths (relative to the directory) of all files that should be exported, manually sorted
* Modified the logic in the exporter to take that array instead of some filters, and pass it as-is to the exporter
* Added appropriate GUI elements to the project properties dialog that allow the modification of that list with easy to understand controls

### In Detail

When you open a directory's project properties, the Files-tab has now changed. See the image below for a description of the various elements:

image

### Migration

User migration is simple: After the upgrade, the glob patterns will be gone, and instead an empty file array will be shown. **This feature is backwards-compatible.** Should the user downgrade (which is not recommended, but, you know…) the file list will simply be replaced with an empty glob pattern list again.

### Timeline

This PR should be once confirmed with @sensologica. In addition, someone with a **Windows PC and Linux or Mac** should test this out, because I'm a bit afraid of what will happen with cross-platform compatibility given the different path separators on Win and \*nix. It should work, but you never know.

Tested on: macOS Sonoma 14.2.1

***

EDIT: Fixes #4966

### CODE REVIEW

**Comment by nathanlesage** [comment]
Quick update: I'll probably merge this PR after Monday's nightly. It works pretty stable, and any additional bugs that may occur can be captured during the remaining betas.

**Comment by kyaso** [comment]
> Quick update: I'll probably merge this PR after Monday's nightly. It works pretty stable, and any additional bugs that may occur can be captured during the remaining betas.

Shall I still have a look over the PR, or is it not required if you are going to merge anyway? 🤔

**Comment by nathanlesage** [comment]
If you manage please do so! I said this mainly because I don't know what your availability right now looks like!

**Comment by nathanlesage** [comment]
@kyaso I'll now merge the PR since we really need a new beta release, and I want to progress. But so that you in the future have the ability to do PRs, it would be great if you could shoot me a mail to indicate what time horizon I could plan with. That would give me the opportunity to match larger changes as this one to your availability, and I generally do believe that code reviews are a good way of improving code quality. But for that we have to coordinate a bit better :D (Don't get me wrong, this incoordination is on me, because I myself urgently needed this feature.)

**Pull request merged**
