### PR TITLE
WIP: Better native look on Linux

### PR DESCRIPTION
**Pull request by Elarnon**
## Description

Add a (more) native look-and-feel to Zettlr on Linux following modern Gnome apps, with a bunch of CSS borrowed from adwaita.

<details>
<summary>Comparison between old and new styles</summary>

| | New | Old |
| -- | -- | -- |
| Berlin (light) | New Berlin Light 2022-10-11 15-24-53 | Old Berlin Light 2022-10-11 15-30-32 |
| Bielefeld (light) | New Bielefeld Light 2022-10-11 15-25-22 | Old Bielefeld Light 2022-10-11 15-31-09 |
| Bordeaux (light)  | New Bordeaux Light 2022-10-11 15-25-42 | Old Bordeaux Light 2022-10-11 15-31-15 |
| Berlin (dark)  | New Berlin Dark 2022-10-11 15-25-54 | Old Berlin Dark 2022-10-11 15-31-24 |
| Bielefeld (dark)  | New Bielefeld Dark 2022-10-11 15-26-04 | Old Bielefeld Dark 2022-10-11 15-31-29 |
| Bordeaux (dark)   | New Bordeaux Dark 2022-10-11 15-26-14 | Old Bordeaux Dark 2022-10-11 15-31-35 |
| Distraction-free mode | New Distraction Free Mode 2022-10-11 15-28-36 | Old Distraction Free Mode 2022-10-11 15-32-34 |
| Preferences | New Preferences 2022-10-11 15-29-06 | Old Preferences 2022-10-11 15-31-48 |
| Print window | New Print Window 2022-10-11 15-29-37 | Old Print Window 2022-10-11 15-33-12 |
| Menu | New Menu 2022-10-11 15-29-25 | Old Menu 2022-10-11 15-32-59 |
| Popover | New Popover 2022-10-11 15-29-56 | Old Popover 2022-10-11 15-33-20 |

</details>

The PR also provides integration with the system colors, using default Gnome colors for the window instead of theme-specific ones (the preference for this currently hijacks the pre-existing "Use system accents" preference that was
 previously not available on Linux).

<details>
<summary>Comparison of theme colors and system colors outside the text area</summary>

| | Theme colors | System colors |
| -- | -- | -- |
| Berlin (light) | New Berlin Light 2022-10-11 15-24-53 | Berlin System Light 2022-10-11 15-26-43 |
| Bielefeld (light) |  New Bielefeld Light 2022-10-11 15-25-22 | Bielefeld System Light 2022-10-11 15-26-50 |
| Bordeaux (light) | New Bordeaux Light 2022-10-11 15-25-42 | Bordeaux System Light 2022-10-11 15-26-56 |
| Berlin (dark) | New Berlin Dark 2022-10-11 15-25-54 | Berlin System Dark 2022-10-11 15-27-06 |
| Bielefeld (dark) | New Bielefeld Dark 2022-10-11 15-26-04 | Bielefeld System Dark 2022-10-11 15-27-14 |
| Bordeaux (dark) | New Bordeaux Dark 2022-10-11 15-26-14 | Bordeaux System Dark 2022-10-11 15-27-22 |

</details>

## Work-in-progress

This PR is a work-in-progress, and I can't promise all the elements of the checklist have been taken care of. I am making a WIP pull-request to start a discussion and make my current changes available: what I originally intended to be a few simple CSS tweaks has clearly overgrown its original scope (and the time I had allocated to it), and I would love to have some feedback from Zettlr developers and users to figure out if there is interest in polishing it up into something that can actually be merged.

More precisely, following the provided checklist, the following needs to be tackled:
 - [ ] Document the code, in particular the new `zettlr-splitter` component, the window layout using CSS grid, and the interaction between the pre-existing CSS variables from themes and the new CSS variables used by the linux style sheet.
 - [ ] Test on Windows and macOS systems that everything still works.  I do not have access to any of these platforms, and everything looks fine to me when overriding the `platform` in the Vue component, but tests on a real platform would be best.
 - [ ] Run `yarn lint` and `yarn test`
 - [ ] Add an entry to the CHANGELOG.md, or maybe multiple entries if this PR should be split up into parts.

## Changes

Most of the changes are CSS changes scoped to `body.linux` and `body.linux.dark` and should not impact other platforms.  However, some of the changes are more involved, in particular:

 - I had many issues with things ending up on the wrong positions when changing dimensions, so a lot of absolute positioning has been replaced with a CSS grid layout, on all platforms.  This simplifies a bunch of related code (both in JS and CSS) that no longer has to take care of setting margins and offsets properly as we rely on the layout engine instead.
 - Related, the SelectableList layout has been re-done using flexbox and has not been tested for correctness as extensively as it should have, because I had already overspent my time budget for working on this when I reached that point.
 - I moved the code setting the userData directory above the code taking the instance lock, because there is a different instance lock for different userData directories.  This really has nothing to do in this PR, but it is a separate commit, so can easily be split off into a separate PR or be removed entirely if that is not the behavior Zettlr wants.
 - The SplitView component has been entirely rewritten and replaced with an over-engineered and under-documented (sorry) custom component that I got nerdsniped into writing.
   I wrote it because the previous implementation's custom layout computations were fairly brittle due to assuming that the component occupies the full window initially, which caused issues (read: horizontal overflows) both due to the SplitView containing the sidebar and (I believe) some of my experiments with borders in frameless windows.
   The replacement does not do any layout computation[^1], and instead entirely relies on the CSS flexbox model for layout computations, including growth/shrink factors[^2] and min/max widths.  Most of the complexity comes from the algorithm that tries to figure out the *visual* predecessor and *visual* successors of a separator in order to support the CSS `order` property; this could easily be culled and replaced with a simpler (but arguably less "correct") implementation.
   The replacement is also a native WebComponent, not a Vue component, which may or may not need to be changed for Zettlr (I wrote it as a native WebComponent because I have other projects where I want to use it, and those projects do not use Vue).
 - The popover code has been slightly changed to debounce layout computation using `requestAnimationFrame` instead of a 100ms `setTimeout`, avoiding the previous flash of improper layout when the popover's content changes.  For some reason the explicit call to `_place` inline did not work for that purpose, I assume this is due to some layout information not being available at that time.

In terms of style changes, I have tried to follow the [Gnome Human Interface Guidelines](https://developer.gnome.org/hig/) and the [`libadwaita` source code](https://gitlab.gnome.org/GNOME/libadwaita) as closely as possible, although at times I had to compromise with Zettlr's existing components.

## Questions

There are a few things that I'm not sure how to tackle best.

 - Is my use of `useSystemAccent` correct?  There is no mechanism to get the actual "system colors" from electron on Linux, so using the default Adwaita colors here seems sensible to me.  I am not sure whether that (the absence of) that preference should also trigger the extension of theme colors to the window but on the other hand.. there are already so many preference checkboxes.
 - Would Zettlr be interested in integrating the splitter component as-is (if I document it a bit more)? It is simple and decoupled enough that I'd be willing to maintain the component, and I may package it independently someday, but I can also write a dumbed down version that only does what's needed for Zettlr.

## Additional information

Do you really want *more* information?  I didn't think so.
<details>
<summary>Thanks for reading.</summary>

Cute cat and dog

</details>

Tested on: ArchLinux using Electron 17

[^1]: Except for converting from % to px.
[^2]: Elements with nonzero growth factor are not resized explicitely, so putting a separator between two elements with a nonzero growth factor is not supported.  This is a debatable choice that may need to be revisited; the goal was that in a sidebar-content-sidebar layout, only the sidebar widths are set explicitely, not the content.

### CODE REVIEW

**Comment by nathanlesage** [comment]
Looks very impressive, and I really like this initiative! I always felt the Linux styles looked a tad like second-class citizens, simply because I don't have a Linux system to test these things out. Also, it's great to see that getting the system color now also works on Linux!

One question, though: Which version did you base this off of …? I'm seeing several files I thought didn't exist anymore …? Additionally: What specifically is the purpose of this splitter component? Zettlr utilises in several aspects now already such splitters (if I understand its purpose correctly), so what are you using it for …?

Other than that, super great, and I like it. The only thing we need to be wary is that I've severely changed tons of stuff in the app since 2.3, and the Codemirror migration PR (https://github.com/Zettlr/Zettlr/pull/3776) is stupidly large even now, we may want to see where things may collide (and I'd argue we should first merge the Codemirror thing, as this is definitely a prerequisite).

**Comment by Elarnon** [comment]
> it's great to see that getting the system color now also works on Linux!

Note that getting the system color from electron doesn't work on Linux, the system colors are currently hardcoded to return the default Gnome colors as a workaround.

> Which version did you base this off of …? I'm seeing several files I thought didn't exist anymore …?

The `develop` branch (currently rebased on a87e0d99c51694d0a622d192a3ab0e08c466a5fd from September 15th).  Maybe those files were removed in the CoreMirror migration PR?

> What specifically is the purpose of this splitter component? Zettlr utilises in several aspects now already such splitters (if I understand its purpose correctly), so what are you using it for …?
This is a replacement for the existing splitter (the SplitView component is gone in this PR).  I was having inconsistent issues during testing with the existing Zettlr splitter where I would sometimes end up with a total width of file manager + editor + sidebar that was larger than the window width; this new component uses a different approach that doesn't exhibit these issues.

Theoretically this is an orthogonal issue to the rest of this PR, but the new component gets styled differently from the old one, and things got entangled.  I am fine with either splitting off the new component + new styles as a separate PR, or reverting to use the old splitter (in which case I would have to adapt the CSS a little bit), but I didn't want to work toward either resolution without input from you.

> the Codemirror migration PR (https://github.com/Zettlr/Zettlr/pull/3776) is stupidly large even now, we may want to see where things may collide (and I'd argue we should first merge the Codemirror thing, as this is definitely a prerequisite)

I didn't know how usable/WIP it was so I based my work off the `develop` branch, under the assumption that the CodeMirror migration would not impact UI components other than the editor too much.  Should I rebase this PR to target the `codemirror-6` branch instead of the `develop` branch?

**Comment by nathanlesage** [comment]
> Note that getting the system color from electron doesn't work on Linux, the system colors are currently hardcoded to return the default Gnome colors as a workaround.

Ah, alright, so basically what I was doing before with the Zettlr green (`#1cb27e`) as I didn't look up the default colors, so that's perfectly fine!

> Maybe those files were removed in the CoreMirror migration PR?

Very likely. At one point I grew so annoyed with many stupidly complicated things I did previously, that the CM6 PR now is basically a big chunk of everything. Not the best practice, but definitely fixed a ton of issues Zettlr was having before.

> This is a replacement for the existing splitter (the SplitView component is gone in this PR). I was having inconsistent issues during testing with the existing Zettlr splitter where I would sometimes end up with a total width of file manager + editor + sidebar that was larger than the window width; this new component uses a different approach that doesn't exhibit these issues.

Yeah, the SplitView component was a little bit hacky all along as it was difficult for me to get things right. If you found a better solution, then please, albeit I would definitely argue to split this off into its own PR if possible. If that would require too much work, then we can leave it in this PR here. One thing we might want to check is how different that splitter works with regard to the new `EditorBranch` components which – I think – are much better regarding the splitting. We might want to unify that behavior, if that is possible (less code + if we change styles that is reflected everywhere, not just one component). Feel free to have a look.

> Looks like my assumptions were right. I have rebased (locally) these changes on top of codemirror-6 and besides a couple trivial merges (we both fixed a typechecking issue in fsal-directory.ts, and v-on:jump-to-line="genericJtl($event)" causes a conflict on the sidebar), this PR and https://github.com/Zettlr/Zettlr/pull/3776 seem to be fairly independent.

The `genericJtl` was a fix because when calling `jtl` only with the line itself, it wreaks so much havoc in the main process that afterwards one has to nuke the config file. I learned that the hard way, but in general I want to re-integrate the JTL-functionality into one single file again before finally merging the PR.

> (By the way I just had a quick look at the new CodeMirror due to testing this. It looks great and seems to fix some visual bugs I had been experiencing!)

That was the goal :)

**Comment by nathanlesage** [comment]
Hey @Elarnon – the Codemirror 6 PR is now merged, so your PR is the next on the list!

**Comment by Elarnon** [comment]
Neat!  I have rebased onto current `develop` branch with a cleaned up splitter, but did not have time to test properly.  I'll try to clean things up and finish separating the new splitter into a different PR sometime this week.

**Comment by amwnag** [comment]
Hello, apologies in advance for the bump. 

I'd love to see these UI changes, especially the small things such as the scrollbar and tabs. Will this still be moving forward?

**Comment by Elarnon** [comment]
I had some issues with the merged splitters (don't remember the details at the moment, I think it had to do with overflow) and postponed that last part of the work without ever really coming back to it.

I will try to find some combination of time (and, to be fair, motivation, as I don't really use Zettlr anymore) to rebase this on current `develop` and make a proper PR, but can't promise when that will happen. If someone wants to take this up, feel free to say and do so.

**Comment by nathanlesage** [comment]
@Elarnon Thank you for following up on this. I can absolutely understand if you do not find any time or motivation to finalize this, so don't worry. But since there are so many merge conflicts already, it may make sense to re-open a new PR.

Hence, I'll close this PR, but as they said: Either Elarnon or whoever wants to pick this up can do so, and I'll happily review a new PR! :) (Also, closing this releases pressure on Elarnon to actually finish this, I hope)

**Pull request closed without merging**
