### PR TITLE
Fanzhang new issue

### PR DESCRIPTION
**Pull request by zhangfanfansz**
## Description

Try to fix all the CSS color problems mentioned in issue #1845, meanwhile making sure all the current functionalities and style works properly.

## Changes

We only changed the related CSS code and didn't affect any functionalities-related code.

## Additional information

Tested on: <!-- Windows 10 ->

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you for the PR! So far it does look good. Two points, though:

1. I'm afraid I mingled heavily with the LESS styles in the previous days, explaining the merge conflicts we're having. Would you mind having a look at my latest commits regarding the CSS and adapting, where necessary? (The main thing is that I completely moved the Geometry-Settings to the Window-Registration module, the themes are still there)
2. You changed the readability colours from HSV to RGB. The reason I chose HSV was because it did look better, but I assume you didn't just convert HSV to RGB, but also change the colours, or did I miss something?

**Comment by zhangfanfansz** [comment]
Hi,
1. I have checked the latest commit about CSS, the only code I made the change for geometry is changing the opacity from 0.3 to 0.65 so the symbols can be visible in dark mode. And I didn't find the source/common/modules/window-register/assets/geometry.less in my forked repository and I can't fetch upstream because it says "This branch is 245 commits behind the upstream and has conflicts that must be resolved." So I don't know what I can do with it.

2. Regards the changes in the readability colors. Yes, I changed from HSV to RGB cause I think it's much easier for me to directly see the color in the editor so I don't need to check the specific number for presenting different colors. And I also changed the colors to make them soften when reading in readability mode.

**Comment by nathanlesage** [comment]
> I have checked the latest commit about CSS, the only code I made the change for geometry is changing the opacity from 0.3 to 0.65 so the symbols can be visible in dark mode. And I didn't find the source/common/modules/window-register/assets/geometry.less in my forked repository and I can't fetch upstream because it says "This branch is 245 commits behind the upstream and has conflicts that must be resolved." So I don't know what I can do with it.

Mh, right now it says 50 modified files, which doesn't seem right. In order to bring your own branch up to date, you have to merge in the develop-branch into your feature branch, using a rebase. Here's some more info on that: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/merging-an-upstream-repository-into-your-fork

Try to get the "Changed files" tab on here to get back to the six (?) files or something that you have actually altered.

**Comment by zhangfanfansz** [comment]
I have created a new fork repository for this issue cause I really can't fix those extra file changes because of my previous behavior of empty files.

**Comment by nathanlesage** [comment]
Closing in favour of #1973

**Pull request closed without merging**
