### PR TITLE
Added AppImage support

### PR DESCRIPTION
**Pull request by yashha**
## Description

Adds AppImage building feature for easy installing on every system.

## Changes

- When building linux it will build an AppImage for x64 and ia32.
- Changed artifact name to include the achitecture. Zettlr-linux-${version}-${arch}.${ext}
 I thought version should be before arch but I can change this back if you want.
- Changed file associations array. It was necessary for Appimage building.
  This could maybe have not intendend effects?

## Tested On
 - OS: Debian Ubuntu
 - OS Version: 18.04.03
 - Zettlr Version: v1.5.0-beta.1

### CODE REVIEW

**Comment by nathanlesage** [comment]
Oh, and P.S.: PRs only to the develop-branch, please, I won't merge this into master! Thaaaankss

**Comment by yashha** [comment]
To 2. It seems thats now the standard way to write it. And the longform of markdown is included.
To 3. I put the AppImageTarget into a contant, that looked cleaner.

Should I leave the arch before the version? I think it looks better. Also should I align the other packages then also?

**Comment by nathanlesage** [comment]
Alright, if the long form is also included, why not. Concerning the filenames: I'm not sure whether or not changing the pattern would cause the API to crash, there's a lot of possibility of regression bugs :S I'll have to check its code to make sure! If the API doesn't care then we can certainly switch — is there any "unwritten standard" as to how the artifact names of released files should be? Something like semver for versioning? If so, I'd like to stick to the most widely adopted naming convention. The more common something is, the less other stuff will break when interacting :)

We'd definitely have to tell these guys: https://github.com/Homebrew/homebrew-cask/blob/master/Casks/zettlr.rb …

P.S.: Just checked the API, and it does not care at all, it'll happily eat whatever I feed it! So we can change the artifact name to the most common way of naming them!

In the meantime, I'll quickly test building AppImages on my machine!

**Comment by yashha** [comment]
I just know it from other packages like visual studio code. The naming the other way around seemed odd to me.

https://code.visualstudio.com/Download
https://github.com/ramboxapp/community-edition/releases

Atom has it different:
https://github.com/atom/atom/releases

**Comment by yashha** [comment]
Here not one standard file format, I guess.
https://askubuntu.com/questions/330018/what-is-the-standard-for-naming-deb-file-name

**Comment by nathanlesage** [comment]
:D Well, well. Then we should use some reasonable format. What I've seen with a lot of programs, and which is pretty obvious, is to put the version number behind the name. And concerning sorting, we should start with the artifact parts that are less specific and end with those that are most specific. So this would mean:

`Zettlr-${version}-${platform}-${arch}.${ext}`; so compared to currently just move forward the version.

Besides, I think some variable like `platform` is already supported, I think? If so, we could make the artifact name much more modular. That I left the literal platforms in there was, if I remember correctly, because it wasn't possible back when I first wrote the script. But I'm not sure. Your opinion?

**Comment by yashha** [comment]
Sounds good to me, I'll make a commit.

**Comment by nathanlesage** [comment]
Looks wonderful! I'll be testing it out hopefully today, just to see how it goes, and then I'll merge this thing :)

**Comment by nathanlesage** [comment]
Alright, it seems to work, although I have no chance to test this out due to missing hardware and disk space for virtual images. Do you happen to have a macOS to build and then test on a linux distribution?

**Comment by yashha** [comment]
I have only a linux. It worked there.

**Comment by nathanlesage** [comment]
Mh … I have an idea: Would you be willing of supplying the AppImage for the time being? I'm asking because I can't fix AppImage related problems obviously … In the meantime, I'll just merge that thing because it obviously works and does not interfere with the rest of the build process. :)

**Pull request merged**
