### PR TITLE
Rename Catalan translation file

### PR DESCRIPTION
**Pull request by jordimas**

### CODE REVIEW

**Comment by jordimas** [comment]
I test the following:
- yarn start runs the application and it's shown in Catalan language on the Catalan locale 
- script/i18n.sh works

It seems that just renaming the file is enough. No need to make any change code.

**Comment by nathanlesage** [comment]
Well if I see it correctly you didn't rename the file, only the locale description inside the file? I just did a full text search for `ca-CA` in the codebase and it's really only the file itself that has the wrong language code. In the rest of the app it seems good to go. But yeah, I think renaming the file itself is also in order.

Feel free to run `yarn lint:po` afterwards to lint the files as well to ensure everything is going to plan.

Apparently merging the updated translations caused yet another merge conflict, but if that is resolved I think we can quickly sneak this in to 3.0.0 stable!

**Comment by jordimas** [comment]
Hello. I did rename the file. Github UI is not great at this but notice:

_static/lang/ca-CA.po → static/lang/ca-ES.po_

Captura de pantalla de 2023-08-31 19-20-50


I did run yarn _lint:po_ now and it reports no error:
```
Parsing ar-AR.po...
Parse successful!
Parsing ca-ES.po...
Parse successful!
Parsing cs-CZ.po...
```

Thanks

**Comment by nathanlesage** [comment]
Alright, perfect, sorry for not noticing — but I think you still have to do a rebase, GitHub is still complaining that I can't merge the PR :/

**Comment by jordimas** [comment]
I sync the branch and you should be able to merge now. Thanks!

**Comment by jordimas** [comment]
Any chance to merge this? There are some translation fixes that I will like to propose but this needs to be merge first. Thanks

**Comment by nathanlesage** [comment]
@jordimas Sorry, I totally forgot about the PR, and now there are merge conflicts again :(

As you mentioned that you have some additional fixes in the pipeline, I just quickly renamed the file myself, this makes it faster than to resolve merge conflicts!

**Pull request closed without merging**
