### PR TITLE
Tray QuickNote

### LINKED ISSUE #175: [Feature Request] Tray QuickNote
When implementing a Zettelkasten, what you might want to do is have the option to quickly enter new thoughts into it. Therefore, we'll implement a Tray icon enabling a quick entry. This feature is targeted towards the `1.4` release, if possible.

## Proposed solution

1. In the preferences, enable the Tray QuickNote and set several options for easy access, such as:
    - The folder in which they are placed automatically
    - File name patterns (such as: `%id %firstline.md` for example)
2. When you have a thought or find something online, simply click on the Tray icon to bring up the quick entry window
3. Enter the thought using standard Markdown, highlighted using Zettlr's theme
4. Add links, tags and what else you need
5. Possibly overwrite the target folder and the filename
6. Click "Create" and have the note added to your Zettelkasten.

## ToDos

- [ ] Add a window class
- [ ] Add a service provider for the Tray Window
- [ ] Add a command to enter the final note
- [ ] Solve the Tray limitations on Linux systems. See the [Tray Class Documentation](https://electronjs.org/docs/api/tray)
- [ ] Testing

### PR DESCRIPTION
**Pull request by cskeogh**
## Description
Add a tray in the system's notification area with menu items: `Show Zettlr` & `Quit`. Defaults to off, controlled by advanced preference: `Leave app running in the notification area` or `Show app in the notification area` (MacOS)

Tray on Windows 10

## Changes
@nathanlesage Thank you for your great reviews on the earlier pull requests #2026 and #1959.  
[Our team](https://github.com/UofA-SPI21-team7) has worked hard and incorporated all the comments.

Full detail of the changes are in [tray design](https://github.com/UofA-SPI21-team7/zettlr-assignment/wiki/Tray-design).

From the [tray design](https://github.com/UofA-SPI21-team7/zettlr-assignment/wiki/Tray-design) I would like to highlight the following recent design change in response to https://github.com/Zettlr/Zettlr/pull/2026#discussion_r645963610 - icon is removed, text is grey and smaller.

Screenshot from 2021-06-08 12-53-52

## Translation Strings

After merging please add the following translation strings:

```json
{
    "dialog": {
        "preferences": {
            "leave_app_running_in_the_notification_area": "Leave app running in the notification area",
            "show_app_in_the_notification_area": "Show app in the notification area"
        }
    },
    "system": {
        "error": {
            "tray_not_supported": "Tray is not supported. Gnome Extension &quot;KStatusNotifierItem/AppIndicator Support&quot; is required for Tray support on the Gnome Desktop."
        }
    },
    "tray": {
        "show_zettlr": "Show Zettlr",
        "tooltip": "This is the Zettlr tray.\nSelect Show Zettlr to show the Zettlr app.\nSelect Quit to quit the Zettlr app."
    }
}
```

## Additional information
Tested on:

 - Windows 10
 - MacOS
 - Linux Fedora 33 Gnome Desktop
 - Linux Fedora 33 KDE Desktop
 - Debian 10 XFCE Desktop

### Checklist

  - [x] I documented all behaviour as far as I could do.
See our teams pull request https://github.com/Zettlr/zettlr-docs/pull/103
  - [x] I target the develop-branch, and *not* the master branch.
  - [x] I have tested this extensively and paid extra attention to
        potential cross-platform issues (e.g. Cmd/Ctrl/Super-key bindings)
  - [x] I have made use of ESLint using the provided configuration from the
        repository's .eslintrc.json file, and it did not complain.
  - [x] I have added an entry to the CHANGELOG.md.
  - [x] I matched my code-style to the repository (as far as possible).
  - [x] I do agree that my code will be published under the GNU GPL v3 license.
  - [x] As far as JS-files are concerned, I made sure to copy (in case of new files)
        or adapt (in case of existing files) the info in the header.
  - [x] I synced the latest commits to develop shortly before proposing
        so that no merge issues occur.

Closes #175

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you so much for the new PR! I have two things to say, one which I realised after your last PR, and one that I just stumbled upon trying to test your PR.

#### 1. `trans` doesn't like being called during boot

Before I was able to test the PR, there was a nice error message:

image

The reason is that you're calling the `trans` function before the translations have actually been instantiated. As you can see in the `lifecycle.ts` file, the translations are being loaded after the service providers are instantiated. This is also, why in line 176 the menu provider is being told to "set" the application menu – *after* the translations have been loaded. I would suggest to remove all calls to `trans` from the constructor of the TrayProvider, and instead move these to a separate function, e.g., `init` that is being called after the menu provider in that line (or before, I don't really care, as long as it's after the loading of the translations).

#### 2. What about the bundling of libraries on the GitHub CI?

This is a point that I suddenly had after your last PR: Since we need to ship the libraries with AppImages, they must be present on the system. We are building on a non-GUI system, a virtual machine, so I was thinking: Are these needed libraries present on the GitHub Ubuntu machines …?

If not, we might need something similar to what I implemented in the file `scripts/get-pandoc.sh` to download that said library in the CI pipeline. Since I've never dealt with native libraries, I'm actually unsure of how to do that.

Do you have an idea for that?

***

BUT! Other than that, I just tested the PR and except the first issue it works like a charm — and thus can be merged after the issue is resolved! Plus, thank you actually for uncovering the issue, I'll be adding an additional check in the `trans`-function to make sure it doesn't prohibit start up if something like this happens in the future :)

**Comment by cskeogh** [comment]
Thank you kindly for the great review. Will fix issue 1.

> If not, we might need something similar to what I implemented in the file `scripts/get-pandoc.sh` to download that said library in the CI pipeline. Since I've never dealt with native libraries, I'm actually unsure of how to do that.
> 
> Do you have an idea for that?

Option 1: include the libappindicator binary library for all supported architectures in the Zettlr's GitHub repository. When packaging, bundle the libappindicator binary library from the build system's Zettlr clone.

Option 2: At build time download .deb file from https://packages.ubuntu.com/hirsute/libappindicator3-1 for all supported architectures. Carefully handle mirrors, Ubuntu versions (hirsute, groovy, focal, etc.), unpack the .deb, copy the binary library from the unpack, and bundle.

Which option do you like? Option 1 is easier to implement.

**Comment by nathanlesage** [comment]
Option 1 might have the problem that it might be at some point outdated. The question for that option would be how security relevant this might become?

With regard to option 2: Luckily the GitHub Actions VMs do allow to install packages so running `sudo apt install libappindicator1` should work out of the box. Maybe we need some fiddling with apt to get the ARM one, but in general this does look like an easy way out. (Docs: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners)

What do you think?

**Comment by cskeogh** [comment]
GitHub hosted runners could be a good solution. I will investigate GitHub hosted runners and report back.

**Comment by nathanlesage** [comment]
@cskeogh I found something even better: We can download different architectures easily as well using apt. Instead of calling `apt download libappindicator3-1` we can execute `apt download libappindicator3-1:amd64`. Couldn't test this on my Debian server since it doesn't ship `arm64` versions of libappindicator, but Ubuntu should work, as seen in the repository that you linked.

This would, in general mean that we might be able to fall back onto downloading the `deb`-packages and extracting the library for both amd64 and arm64 and bundle these ones (analogous to how the Pandoc download work).

Looking forward to your results!

Btw, when it comes to configuring apt and dpkg, I found this page: https://wiki.debian.org/Multiarch/HOWTO

**Comment by cskeogh** [comment]
Closing this pull request. Our team will open a new pull request with improvements

**Pull request closed without merging**
