### PR TITLE
updated Tamil translation

### PR DESCRIPTION
**Pull request by TamilNeram**
## Additional information

Tested on: <!-- OS including version ->

### CODE REVIEW

**Comment by nathanlesage** [comment]
Was opening this PR a mistake …?

**Comment by TamilNeram** [comment]
I have reviewed all the translations and updated few translations in Tamil.

**Comment by TamilNeram** [comment]
This PR is a valid one. I help with Tamil Translation for several applications during my free time. 
The Previous commit merged e-mail triggered me to review all the strings once again, As I was not sure if I have proofread the translations or not. So, I did a proofreading of all messages once again and updated the translated strings for Tamil Language. 

It is completed now. Sorry for any inconvenience caused.

**Comment by nathanlesage** [comment]
Ahh alright — no worries, I was a bit confused, but now GitHub shows me that you have modified things. I will merge soon! Thank you for your work, and sorry for the confusion on my end!

**Comment by nathanlesage** [comment]
Hey @TamilNeram I am sorry for forgetting about the PR, but I would like to merge it. For that, it would be great if you could quickly resolve the merge conflicts that we have.

**Comment by TamilNeram** [comment]
Conflict resolved.  @nathanlesage, Please merge and close this PR.

**Comment by nathanlesage** [comment]
Done, thanks.

**Pull request merged**
