### PR TITLE
fix: Zkn autocomplete trigger

### PR DESCRIPTION
**Pull request by kyaso**
## Description

This PR addresses the issue mentioned in https://github.com/Zettlr/Zettlr/issues/4616#issuecomment-1712813695.

Tested on: Linux Manjaro

### CODE REVIEW

**Comment by nathanlesage** [comment]
So this fixes the issue you were observing, right? To me, it looks functional and thus good to go. (There are a few conflicts, though, do you mind going over them?)

**Comment by kyaso** [comment]
> So this fixes the issue you were observing, right?

Yes, this resolves the issue where the autocomplete pop-up would not show up when editing a Zkn link with another link preceding it.

**Comment by nathanlesage** [comment]
Perfect, thank you! Merging now! I appreciate your help, it is really, really nice that you support me in fixing bugs as much as you do.

**Comment by kyaso** [comment]
> Perfect, thank you! Merging now! I appreciate your help, it is really, really nice that you support me in fixing bugs as much as you do.

Anytime!

**Pull request merged**
