### PR TITLE
fix: Removed shift-heading-level-by: 1 flag from defaults files. This was a workaround for Pandoc which is no longer needed.

### PR DESCRIPTION
**Pull request by TeaDrinkingProgrammer**
## Description
See title.

## Changes
On Zettlr 3.0.5, XeLaTex 3.141592653-2.6-0.999996 (MiKTeX 24.3) and Pandoc 3.1.3, when you take the XeLaTeX PDF template and change number-sections from false to true and generate a PDF from this MD file:
```
---
title: "Test"
---
# Chapter 1
## Chapter 1.1
### Chapter 1.1.1
# Chapter 2
# Chapter 3
## Chapter 3.1
```
You get this:
image

When you change the base config and remove:

shift-heading-level-by: 1

And then change number-sections from false to true. This is the result:
image

See #5029

### CODE REVIEW

**Comment by TeaDrinkingProgrammer** [comment]
Do you want me to add this to the CHANGELOG.md?

**Comment by nathanlesage** [comment]
@TeaDrinkingProgrammer If you wouldn't mind adding a section to the top that would be awesome. Feel free to use the following template (make sure to stick with hard-wrapped at 80 columns as the rest of the changelog; I don't have a line here to ensure that):

```markdown
## Changes to Pandoc Profiles

This update fixes a workaround that Zettlr had in place for a shortcoming of Pandoc regarding
the automatic numbering of headings. This workaround is no longer necessary, since Pandoc has
since fixed the issue. From this version onward, Zettlr will ship with changed default
profiles for various export formats. Since Zettlr never overwrites any data, the new defaults
will not be applied automatically. In case you want to use the new settings as well for your
own setup, you have the following options to adapt Zettlr after the update and ensure you use
the new defaults:

* In case you did not modify one of these profiles or are fine with resetting your changes,
  you can just delete them, which will prompt Zettlr to immediately recreate them – but now
  with the new settings
* In case you did modify them and want to keep your changes, rename the file to something
  else – Zettlr will then recreate the profile with the new default settings

You can also manually adapt them by replacing `TODO: INSERT OLD` with `TODO: INSERT NEW`.

The following profiles are affected by this change:

* TODO: List all files as they appear inside the assets manager of Zettlr
```

I leave it to you to find where to place that (trust your gut feeling regarding the importance, it's going to be fine). Also, feel free to adapt that suggestion as you find it useful for people who mostly *use* Zettlr (and not develop as me; I don't have the best view on how to formulate instructions for everyday users).

Thanks again for your work!

**Comment by TeaDrinkingProgrammer** [comment]
Sorry for the radio silence. I normally rely on my email to get notified about updates from GitHub, but my account logged out, and I didn't notice until a quite recently. 

Thanks for the pointers on the changelog text, I have filled in the parts with `TODO` and made others a bit more straight to the point.

**Comment by TeaDrinkingProgrammer** [comment]
@nathanlesage Anything I can do to push this foreward?

**Pull request merged**
