### PR TITLE
Update PopoverTags.vue

### PR DESCRIPTION
**Pull request by Barnamoyy**
## Description

Fixes issue #5138 where the tag filter didn't get focused after clicking once, It had to be clicked twice to register the typed text. This issue was observed on Linux platform.

## Changes

The code changes line 110 in file https://github.com/Zettlr/Zetttlr/blob/develop/source/win-main/PopoverTags.vue by replacing the onBeforeMount hook with onMounted hook.

## Additional information

None

Tested on: macOS

### CODE REVIEW

**Review by kyaso — CHANGES_REQUESTED** [review]
Thanks for your contribution!
Just a small remark (see review). Also, would you mind adding an entry to our changelog (located in the project root)? You could add quick line mentioning your fix under the "GUI and Functionality" section!

**Comment by chiphogg** [comment]
@Barnamoyy, it looks like maybe this PR has started to slip through the cracks.  I think it's very close to being ready to land.  Do you think you'll be able to finish it up any time soon?

**Comment by chiphogg** [comment]
> Thanks for your contribution! Just a small remark (see review). Also, would you mind adding an entry to our changelog (located in the project root)? You could add quick line mentioning your fix under the "GUI and Functionality" section!

@kyaso, the original author appears to have abandoned this PR.  At the very least, we've had radio silence from them for multiple months, despite direct mentions.

This PR purports to fix my number one biggest nuisance regression in Zettlr.  :slightly_smiling_face:  Therefore, I created a new PR, #5444, which includes this PR's commit (so @Barnamoyy will still get credit), but also addresses your feedback so that we can get it landed.

WDYT about reviewing #5444 instead?  I didn't perform any tests, but I'll let you decide which ones you'd need to see to be confident that the change is correct.

**Comment by nathanlesage** [comment]
Sounds good, I've let the unit tests run but it's basically perfect, will close this one and merge the other one as soon as the tests finish. Thanks!

**Pull request closed without merging**
