### PR TITLE
Create render-emphasis.md

### PR DESCRIPTION
**Pull request by Redsandro**
It's a start.

## Description

List for emphasis tests per request

## Changes

Added .md file to test files

## Additional information

Tested on: <!-- OS including version ->

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thanks for this list! The complex matches are a great start, since these aren't yet handled correctly:

image

I would also propose to repeat these matches with asterisks only. The reason is that I found that asterisks are counted as word-characters by JavaScript regexes, other than underscores, so we should differentiate between underscores and asterisks.

**Comment by nathanlesage** [comment]
Specifically, I think nested emphasis is still a problem

**Comment by nathanlesage** [comment]
Why wasn't this merged …? Did I simply … forget it?

**Comment by Redsandro** [comment]
I think we all forgot :laughing: although now I remember you suggested this PR, so I suggest you merge it. ;)

**Comment by nathanlesage** [comment]
Your suggestion suggests that I suggestively forgot about my own words and will henceforth retreat in shame now. (after merging) 🙈

**Pull request merged**
