### PR TITLE
i18n: Fix typo in french translation ("% s" instead of "%s")

### PR DESCRIPTION
**Pull request by BAKFR**

### CODE REVIEW

**Comment by nathanlesage** [comment]
Thank you for spotting that! Nevertheless, the translations are managed over at [Zettlr Translate](https://translate.zettlr.com). The four default language files are in source control here so that anybody cloning the repository has them available! If you'd be able to apply the fixes there, I would be greatful!

**Comment by BAKFR** [comment]
My bad, I didn't see that.
I'm on my way to fix it the proper way.

**Comment by BAKFR** [comment]
Done, but the fixes will not be effective until someone else has approved the translations I've added.

**Comment by nathanlesage** [comment]
I've approved them, should work now! Thanks again :)

**Pull request closed without merging**
