### PR TITLE
Add missing menu ID

### PR DESCRIPTION
**Pull request by kyaso**
## Description

Fix for #2245.

## Changes

Added missing ID field. ID contains file name.

## Additional information

Tested on: Linux manjaro 5.14.21-2

### CODE REVIEW

**Comment by kyaso** [comment]
Ah, before we merge that, I should also add a Changelog entry. I will do that today.

**Review by nathanlesage — CHANGES_REQUESTED** [review]
Looks good, and since it's in main the click-handler should run, correct? If so, then go ahead!

But we shouldn't use the `path.basename`, because that won't be unique for two times the same filename. Two options: Either use the full path (should be fine since it's just a string, but better test it out, sometimes Electron breaks in the weirdest places) or the almost antique hash!

**Review by nathanlesage — APPROVED** [review]
Looks good! I presume this also works as expected when you click items, right? Then we can go ahead and merge!

**Comment by kyaso** [comment]
> I presume this also works as expected when you click items, right?

When I tested it, clicking on a recent document opened that file as expected. Is that what you mean?

**Comment by nathanlesage** [comment]
Yessssss!

**Pull request merged**
