### PR TITLE
Follow ZTN links on middle click

### PR DESCRIPTION
**Pull request by zh217**
Follow ZTN links on middle click, for https://github.com/Zettlr/Zettlr/issues/2874

## Description

Previously, ZTN links are followed when ctrl/cmd clicking on them. With this patch, the links are also followed with middle clicks, thus enabling keyboard-free navigation.

## Changes

Simply taking middle clicks into consideration when deciding whether to follow links

## Additional information

This is consistent with expected behaviour in browsers where ctrl/cmd clicks on links are equivalent to middle clicks (open link in new tab in the background in Chrome)

Tested on: MacOS 12, Windows 10

### CODE REVIEW

**Comment by nathanlesage** [comment]
I am not sure we should do that. The middle-click is reserved for force-opening something in a new tab (not yet implemented). Once implemented it will work like this:

1. Cmd/Ctrl-Clicking a link will open it, in the current tab if the "Avoid new tabs" setting is present
2. Cmd/Ctrl-Clicking a link using the middle mouse will always open it in a new tab

**Comment by zh217** [comment]
How about:

* ctrl-click or middle-click opens link according to setting
* ctrl-middle-click opens link in new tab always (still, I think this combination is a little strange, but I guess people can get used to it)

**Comment by nathanlesage** [comment]
> still, I think this combination is a little strange, but I guess people can get used to it

What do you think is strange with this? What would you do if you could remap everything at will?

(We possibly can't since people are already used to a certain way of behavior, and changing that might be very difficult)

**Comment by zh217** [comment]
It is strange for me because only when my mouse does not have a middle button do I try to ctrl-click to see what happens, as for the applications I frequently use these two are usually the same.

BTW I tried to find some applications where the two are not the same

* VSCode: ctrl-click follows link (opens in browser), middle-click no-op, and on mouse-over link there is an immediate popup with a '"follow link" (cmd+click)' prompt, the "follow link" part is itself a link and can be clicked, is right above the cursor so that minimal further mouse movement is required. I consider this to be a very good solution since it is very fast after getting used to it and has the further benefit of discoverability. Also It is important to ensure functionality in the absence of middle button (e.g. most people do not know how to middle click on a trackpad).
* Microsoft Word: any click you do except right click opens the link in the browser. The only way to edit a link is to move the cursor using the arrow keys, or backspace/delete. This makes no sense at all, since (unlike in Zettlr) I don't see why anyone would want to follow links in Word.

**Comment by nathanlesage** [comment]
Mh, with regard to your discovery in VSCode: Zettlr also has those tooltips, but they open after some delay. Would having them open immediately remedify that issue in your view?

**Comment by zh217** [comment]
> Zettlr also has those tooltips, but they open after some delay. Would having them open immediately remedify that issue in your view?

I don't think those tooltips are clickable at the moment. If they were, then yes.

**Comment by nathanlesage** [comment]
> I don't think those tooltips are clickable at the moment. If they were, then yes.

Shall we do that instead, then? This would make the change more "backward-compatible". What do you think?

**Comment by zh217** [comment]
Yes, and it would support more devices too (Apple's magic mouse cannot trigger middle clicks either)

**Comment by nathanlesage** [comment]
Okay, then I'm going to close this PR and add said button to the tooltips containing the note preview.

**Pull request closed without merging**
